# Generated by Django 4.2.4 on 2023-09-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carId', models.IntegerField(max_length=255)),
                ('carBrand', models.CharField(max_length=60)),
                ('carModel', models.CharField(max_length=60)),
            ],
        ),
    ]
