# Generated by Django 4.2.4 on 2023-09-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDealershipAPI', '0002_alter_cars_carid'),
    ]

    operations = [
        migrations.CreateModel(
            name='carProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carBrand', models.CharField(max_length=60)),
                ('carModel', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='cars',
        ),
    ]
